name: Sync data with skycity

on:
  push:
    branches: [ main ]

jobs:
  skycity-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Run
        run: cd skycity-parser/SkycityParser && dotnet run ../../data
      - name: Check if there are changes
        env:
          GH_TOKEN: ${{ secrets.GIT_HUB_TOKEN }}
        run: |
          [[ -z $(git status -uno --porcelain) ]] && gh run cancel ${{ github.run_id }}
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_HUB_TOKEN }}
          branch: ${{ github.head_ref }}
